# Vulture whitelist — suppresses false positives in dead-code detection.
#
# AUTO-GENERATED. Do not hand-edit. Regenerate after adding/removing tools,
# models, or enum values with:
#     make lint           # runs vulture against this file
#     docker compose --profile lint run --rm vulture-whitelist > vulture_whitelist.py
#
# Entries are MCP tool functions (discovered at runtime via @mcp.tool),
# pydantic model_config/validators, StrEnum members compared by value, and
# IsolatedAsyncioTestCase async setup/teardown — all invoked indirectly, so
# vulture can't see the use site.

model_config  # unused variable (src/threatray_mcp/config.py:34)
model_config  # unused variable (src/threatray_mcp/models/ai_analysis.py:13)
model_config  # unused variable (src/threatray_mcp/models/ai_analysis.py:45)
model_config  # unused variable (src/threatray_mcp/models/ai_analysis.py:64)
model_config  # unused variable (src/threatray_mcp/models/analyses.py:36)
model_config  # unused variable (src/threatray_mcp/models/capa.py:11)
PUBLIC  # unused variable (src/threatray_mcp/models/common.py:28)
CREATED  # unused variable (src/threatray_mcp/models/common.py:47)
PROCESSING  # unused variable (src/threatray_mcp/models/common.py:49)
STATIC  # unused variable (src/threatray_mcp/models/common.py:59)
LOW  # unused variable (src/threatray_mcp/models/common.py:66)
HIGH  # unused variable (src/threatray_mcp/models/common.py:68)
UNKNOWN  # unused variable (src/threatray_mcp/models/common.py:80)
UNKNOWN  # unused variable (src/threatray_mcp/models/common.py:88)
RAW  # unused variable (src/threatray_mcp/models/common.py:89)
PE  # unused variable (src/threatray_mcp/models/common.py:90)
UNSET  # unused variable (src/threatray_mcp/models/common.py:96)
X86_32  # unused variable (src/threatray_mcp/models/common.py:97)
X86_64  # unused variable (src/threatray_mcp/models/common.py:98)
model_config  # unused variable (src/threatray_mcp/models/files.py:15)
model_config  # unused variable (src/threatray_mcp/models/files.py:27)
model_config  # unused variable (src/threatray_mcp/models/files.py:43)
_.validate_output_path  # unused method (src/threatray_mcp/models/files.py:52)
model_config  # unused variable (src/threatray_mcp/models/functions.py:13)
model_config  # unused variable (src/threatray_mcp/models/samples.py:11)
model_config  # unused variable (src/threatray_mcp/models/search.py:27)
model_config  # unused variable (src/threatray_mcp/models/search.py:56)
model_config  # unused variable (src/threatray_mcp/models/submissions.py:79)
_._check_raw_binary_combo  # unused method (src/threatray_mcp/models/submissions.py:201)
model_config  # unused variable (src/threatray_mcp/models/submissions.py:237)
_._vurl  # unused method (src/threatray_mcp/models/submissions.py:277)
model_config  # unused variable (src/threatray_mcp/models/submissions.py:289)
server  # unused variable (src/threatray_mcp/server.py:23)
threatray_get_ai_analysis  # unused function (src/threatray_mcp/tools/ai_analysis.py:20)
threatray_list_ai_analyses  # unused function (src/threatray_mcp/tools/ai_analysis.py:74)
threatray_get_ai_analysis_by_id  # unused function (src/threatray_mcp/tools/ai_analysis.py:98)
threatray_get_latest_ai_job  # unused function (src/threatray_mcp/tools/ai_analysis.py:116)
threatray_get_analysis  # unused function (src/threatray_mcp/tools/analyses.py:27)
threatray_get_osint  # unused function (src/threatray_mcp/tools/analyses.py:52)
threatray_list_analyses  # unused function (src/threatray_mcp/tools/analyses.py:81)
threatray_list_endpoint_scan_analyses  # unused function (src/threatray_mcp/tools/analyses.py:110)
threatray_get_capa  # unused function (src/threatray_mcp/tools/capa.py:14)
threatray_get_file_metadata  # unused function (src/threatray_mcp/tools/files.py:18)
threatray_get_strings  # unused function (src/threatray_mcp/tools/files.py:45)
threatray_download_file  # unused function (src/threatray_mcp/tools/files.py:87)
threatray_list_functions  # unused function (src/threatray_mcp/tools/functions.py:19)
threatray_get_code_detections  # unused function (src/threatray_mcp/tools/functions.py:55)
threatray_retrohunt_functions  # unused function (src/threatray_mcp/tools/functions.py:92)
threatray_diff_functions  # unused function (src/threatray_mcp/tools/functions.py:132)
threatray_get_sample  # unused function (src/threatray_mcp/tools/samples.py:14)
threatray_search  # unused function (src/threatray_mcp/tools/search.py:19)
threatray_retrohunt_sample  # unused function (src/threatray_mcp/tools/search.py:80)
threatray_list_submissions  # unused function (src/threatray_mcp/tools/submissions.py:26)
threatray_get_task  # unused function (src/threatray_mcp/tools/submissions.py:42)
threatray_get_task_by_analysis  # unused function (src/threatray_mcp/tools/submissions.py:58)
threatray_list_tasks  # unused function (src/threatray_mcp/tools/submissions.py:70)
threatray_submit_sample  # unused function (src/threatray_mcp/tools/submissions.py:91)
threatray_submit_url  # unused function (src/threatray_mcp/tools/submissions.py:142)
threatray_submit_endpoint_scan_archive  # unused function (src/threatray_mcp/tools/submissions.py:167)
threatray_submit_minidump  # unused function (src/threatray_mcp/tools/submissions.py:191)
threatray_submit_mans_file  # unused function (src/threatray_mcp/tools/submissions.py:207)
DUMMY_OSINT_AUTHOR  # unused variable (tests/dummies.py:29)
SHA1  # unused variable (tests/integration/test_all_tools_smoke.py:25)
MD5  # unused variable (tests/integration/test_all_tools_smoke.py:26)
_.asyncSetUp  # unused method (tests/unit/client/test_ai_analysis.py:18)
_.asyncTearDown  # unused method (tests/unit/client/test_ai_analysis.py:23)
_.asyncSetUp  # unused method (tests/unit/client/test_analyses.py:14)
_.asyncTearDown  # unused method (tests/unit/client/test_analyses.py:19)
_.asyncSetUp  # unused method (tests/unit/client/test_capa.py:16)
_.asyncTearDown  # unused method (tests/unit/client/test_capa.py:21)
_.asyncSetUp  # unused method (tests/unit/client/test_files.py:17)
_.asyncTearDown  # unused method (tests/unit/client/test_files.py:22)
_.asyncSetUp  # unused method (tests/unit/client/test_functions.py:18)
_.asyncTearDown  # unused method (tests/unit/client/test_functions.py:23)
_.asyncSetUp  # unused method (tests/unit/client/test_http.py:24)
_.asyncTearDown  # unused method (tests/unit/client/test_http.py:28)
_.asyncSetUp  # unused method (tests/unit/client/test_jobs.py:16)
_.asyncTearDown  # unused method (tests/unit/client/test_jobs.py:21)
_.asyncSetUp  # unused method (tests/unit/client/test_samples.py:15)
_.asyncTearDown  # unused method (tests/unit/client/test_samples.py:20)
_.asyncSetUp  # unused method (tests/unit/client/test_search.py:16)
_.asyncTearDown  # unused method (tests/unit/client/test_search.py:21)
_.asyncSetUp  # unused method (tests/unit/client/test_submissions.py:16)
_.asyncTearDown  # unused method (tests/unit/client/test_submissions.py:21)
